---
title:  "Business Review"
author: "Roho's Group"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  pdf_document:
editor_options: 
  chunk_output_type: console

---


```{r, echo=FALSE}

# 
#  htmltools::img(src = knitr::image_uri("www/rohos.png"),
#                 style = 'position:absolute; top:70px; right:60px;',
#                 height = ".65", width = "15%")

```

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```



```{r librerias, include=FALSE}

library(tidyverse)
library(lubridate)
library(knitr)
library(tidyquant)
library(gt)
library(googlesheets4)
library(janitor)
library(gridExtra)
library(xml2)



```


```{r cleaning, include=FALSE}

# data cleaner 
 cleaner <- function(file){

file_name <-   paste0(file,".xlsx")
setwd("C:/Users/andre/Downloads")

data <- openxlsx::read.xlsx(file_name) %>% as_tibble()
data <- data[-1:-2,-1]
names(data) <- as.character(data[1,])
tibble <- data %>% janitor::clean_names()

transact_tibble <- tibble[-1,] %>% filter(date != is.na(date))%>%
  mutate_all(., str_trim) %>% mutate(amount = as.double(amount)) %>%
  mutate(date = as.Date(date, tryFormats = c("%m/%d/%Y"),optional = F )) %>%
  rename(type = transaction_type,memo = memo_description) %>%
  mutate(creation_date = lubridate::parse_date_time(create_date, orders="mdy HMS")) %>%
  mutate(modification_date = lubridate::parse_date_time(last_modified, orders="mdy HMS")) %>%
  arrange(desc(creation_date)) %>% select(-create_date,-last_modified)


openxlsx::write.xlsx(transact_tibble,file_name)

return(transact_tibble)


 }

# setwd()
setwd("C:/Users/andre/Downloads")

# # cleaned data 
transact <- cleaner("transactions")


```



```{r mother_function, include=FALSE}

# setwd()
setwd("C:/Users/andre/Downloads")



profit_estimator <- function(i_date,f_date){ 
  
  
transactions <- transact %>% filter(between(date,as.Date(i_date),as.Date(f_date)))  
  
# minimalist queries 


operational_income <- transactions %>% 
  replace_na(list(amount=0)) %>% 
  filter(grepl(".Operational Income:",account)) 

material_income <- transactions %>% 
  replace_na(list(amount=0)) %>% 
  filter(grepl("Material Income:",account))

direct_labor <- transactions %>% 
  replace_na(list(amount=0)) %>% 
  filter(grepl("Direct Labor",account)) 

direct_material <- transactions %>% 
  replace_na(list(amount=0)) %>% 
  filter(grepl("Direct Material",account)) 


# Distributions -----------------------------------------------------------

operational_income_dist <- operational_income %>%
  group_by(type,date) %>%
  summarise(n = n(),amount = sum(amount),
            .groups="drop") %>%
  mutate(account = "operational_income" )

material_income_dist <- material_income %>%
  group_by(type,date) %>%
  summarise(n = n(),amount = sum(amount),
            .groups="drop") %>%
  mutate(account = "materials_income" )

direct_labor_dist <- direct_labor %>%
  group_by(type,date) %>%
  summarise(n = n(),amount = sum(amount),
            .groups="drop") %>%
  mutate(account = "direct_labor" )

direct_material_dist <- direct_material %>%
  group_by(type,date) %>%
  summarise(n = n(),amount = sum(amount),
            .groups="drop") %>%
  mutate(account = "direct_material" )


# Grouped by type commutation

accounts_distribution <- operational_income_dist %>%
               bind_rows(material_income_dist,
                         direct_labor_dist,
                         direct_material_dist) %>%
  mutate(year_month = as.yearmon(date, "%Y-%m")) %>%
  mutate(year_quarter = as.yearqtr(date, format = "%Y-%m-%d"))

# RE-grouped overview 

overview <- accounts_distribution %>% 
  group_by(type,account) %>% 
  summarise(cant = sum(n),
            amount=sum(amount),
            .groups = "drop") %>% 
  arrange(account)



# Sense commutation 
cross_tibble_raw <- operational_income %>% 
          bind_rows(material_income,
                    direct_labor,
                    direct_material)%>% 
  mutate(year_month = as.yearmon(date, "%Y-%m")) %>% 
  mutate(year_quarter = as.yearqtr(date, format = "%Y-%m-%d"))


# Detailed Transacts classified

# Acuracy contrasted using 2 diff methods.
profitability <-  cross_tibble_raw %>% 
  replace_na(list(amount = 0)) %>% 
  mutate(source = case_when(str_detect(account,"Income:")~"income",
                            str_detect(account,"Direct Labor")~"labor_cost",
                            str_detect(account,"Direct Material")~"material_cost",
                            TRUE ~ as.character(account)))%>%
  # mutate(source = ifelse(type == "Invoice","income",source)) %>% 
  # mutate(amount = ifelse(source == "income" & amount < 0,amount*-1,amount)) %>% 
   select(-modification_date)
  

# Sumarization & Arithmetics
profit_resumen <- profitability %>%
  group_by(date,source) %>% 
  summarise(amount = sum(amount),.groups = "drop") %>% 
  ungroup() %>% 
  mutate(year_quarter = as.yearqtr(date, format = "%Y-%m-%d")) %>% 
  pivot_wider(names_from = source,
              values_from = amount) %>% 
  replace_na(list(income = 0, 'material_cost' = 0, 'labor_cost' = 0)) %>% 
  mutate(period = substr(date,0,7)) %>% 
  relocate(.before = date,period) %>% 
  group_by(period,year_quarter) %>% 
  summarise(income = sum(income),
            material_cost = sum(material_cost),
            labor_cost = sum(labor_cost),
            .groups = "drop") %>% 
  ungroup() %>% 
  rowwise() %>% 
  mutate(labor_income = income-material_cost) %>% 
  mutate(total_cost = material_cost+labor_cost) %>% 
  mutate(operational_profit = 1-(total_cost/income)) %>% 
  mutate(labor_gross_profit = 1-(labor_cost/labor_income)) %>% 
  mutate(operational_cost = (total_cost/income)) %>% 
  mutate(labor_gross_cost = (labor_cost/labor_income)) %>% 
  mutate(difference = labor_income - labor_cost) %>% 
  ungroup() %>% 
  mutate(year_month = as.yearmon(period, "%Y-%m")) %>% 
  relocate(.after = period,year_month)


quarter_profit_resumen <- profit_resumen %>% 
  group_by(year_quarter) %>% 
  summarise(across(where(is.numeric), ~ sum(.x, na.rm = TRUE))) %>% 
    mutate(operational_profit = 1-(total_cost/income)) %>% 
    mutate(labor_gross_profit = 1-(labor_cost/labor_income)) %>% 
    mutate(operational_cost = (total_cost/income)) %>% 
    mutate(labor_gross_cost = (labor_cost/labor_income))



return(list(
            classified_transactions = profitability,
            accounts_dristribution=accounts_distribution,
            accounts_distribution_overview=overview,
            resumen = profit_resumen,
            quarter_profit_resumen = quarter_profit_resumen
            ))

}

```


```{r data, include=FALSE}


data <- profit_estimator("2020-01-01","2021-03-31")


```


```{r table, include=FALSE}


# profit_resumen = data$resumen
# 
# quarter_profit_resumen <- data$quarter_profit_resumen




```